insert into blogs (id, subject) values(1, 'Mi primer blog');
insert into blogs (id, subject) values(2, 'Blog del Planeta Tierra');
insert into blogs (id, subject) values(3, 'Viviendo sin hijos');
insert into blogs (id, subject) values(4, 'Comiendo bueno-bonito-barato');
insert into blogs (id, subject) values(5, 'Las ocurrencias de Daniel');

insert into posts (id, title, content, blog_id) values(1, 'titulo...', 'contenido...', 1);
insert into posts (id, title, content, blog_id) values(2, 'titulo...', 'contenido...', 1);
insert into posts (id, title, content, blog_id) values(3, 'titulo...', 'contenido...', 1);
insert into posts (id, title, content, blog_id) values(4, 'titulo...', 'contenido...', 2);
insert into posts (id, title, content, blog_id) values(5, 'titulo...', 'contenido...', 2);
insert into posts (id, title, content, blog_id) values(6, 'titulo...', 'contenido...', 2);
insert into posts (id, title, content, blog_id) values(7, 'titulo...', 'contenido...', 2);
insert into posts (id, title, content, blog_id) values(8, 'titulo...', 'contenido...', 2);
insert into posts (id, title, content, blog_id) values(9, 'titulo...', 'contenido...', 3);
insert into posts (id, title, content, blog_id) values(10, 'titulo...', 'contenido...', 3);
insert into posts (id, title, content, blog_id) values(11, 'titulo...', 'contenido...', 3);
insert into posts (id, title, content, blog_id) values(12, 'titulo...', 'contenido...', 3);
insert into posts (id, title, content, blog_id) values(13, 'titulo...', 'contenido...', 3);
insert into posts (id, title, content, blog_id) values(14, 'titulo...', 'contenido...', 3);
insert into posts (id, title, content, blog_id) values(15, 'titulo...', 'contenido...', 3);
insert into posts (id, title, content, blog_id) values(16, 'titulo...', 'contenido...', 4);
insert into posts (id, title, content, blog_id) values(17, 'titulo...', 'contenido...', 4);
insert into posts (id, title, content, blog_id) values(18, 'titulo...', 'contenido...', 4);
insert into posts (id, title, content, blog_id) values(19, 'titulo...', 'contenido...', 4);
insert into posts (id, title, content, blog_id) values(21, 'titulo...', 'contenido...', 4);
insert into posts (id, title, content, blog_id) values(22, 'titulo...', 'contenido...', 4);
insert into posts (id, title, content, blog_id) values(23, 'titulo...', 'contenido...', 4);
insert into posts (id, title, content, blog_id) values(24, 'titulo...', 'contenido...', 4);
insert into posts (id, title, content, blog_id) values(25, 'titulo...', 'contenido...', 4);
insert into posts (id, title, content, blog_id) values(26, 'titulo...', 'contenido...', 5);
insert into posts (id, title, content, blog_id) values(26, 'titulo...', 'contenido...', 5);
insert into posts (id, title, content, blog_id) values(27, 'titulo...', 'contenido...', 5);
insert into posts (id, title, content, blog_id) values(28, 'titulo...', 'contenido...', 5);
insert into posts (id, title, content, blog_id) values(29, 'titulo...', 'contenido...', 5);
insert into posts (id, title, content, blog_id) values(30, 'titulo...', 'contenido...', 5);
